name: destroy the env
on:
  issue_comment:
    types: created
  pull_request_target: 
    types: closed

jobs:
  getting-heaf-ref:
    runs-on: ubuntu-latest
    if: (github.event.issue.pull_request && github.event.comment.body == '/destroy') || github.event.action == 'closed'
    outputs:
      head-ref: ${{ steps.get-head-ref.outputs.result }}
    steps:
      - name: get the pull head ref
        id: get-head-ref
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const prNumber = context.payload.pull_request?.number || context.issue.number;
            const response = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber 
            })
            console.log(response);
            return response.data.head.ref
      - run: echo '${{ toJson(github.event) }}'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Update Pull Request (Start)
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const comment = `### ⏳ Destroy in progress...

            [You can monitor the progress here.](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.number || github.event.issue.number }},
              body: comment
            })
      - name: cache ebcli
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: install ebcli
        id: install-ebcli
        run: pip install awsebcli
      - name: getting issue number
        id: issuse-number
        run: |
          ISSUE_NUM="${{ github.event.number || github.event.issue.number }}"
          echo "issue-number=$ISSUE_NUM" >> $GITHUB_OUTPUT
      - name: getting env name
        id: aws-env-name
        run: echo "aws-env-name=$(aws elasticbeanstalk describe-environments --application-name ${{ vars.AWS_EB_APP_NAME }} --environment-names "nextjs-starter2-demo-pr-${{ steps.issuse-number.outputs.issue-number }}" --query Environments[0].EnvironmentName --output text)" >> $GITHUB_OUTPUT
      - name: getting env status
        id: aws-env-status
        run: echo "aws-env-status=$(aws elasticbeanstalk describe-environments --application-name ${{ vars.AWS_EB_APP_NAME }} --environment-names "nextjs-starter2-demo-pr-${{ steps.issuse-number.outputs.issue-number }}" --query Environments[0].Status --output text)" >> $GITHUB_OUTPUT
      - name: echo of env name and status
        run: |
          echo "${{ steps.aws-env-name.outputs.aws-env-name }}"
          echo "${{ steps.aws-env-status.outputs.aws-env-status }}"
      - name: fail the wrokflow if env not exist
        if: steps.aws-env-name.outputs.aws-env-name == 'None' || steps.aws-env-status.outputs.aws-env-status == 'Terminated'
        run: |
          echo "::error::the env is not exist or it is in terminated state"
          exit 1
      - name: destroy the env
        if: steps.aws-env-name.outputs.aws-env-name != 'None' || steps.aws-env-status.outputs.aws-env-status != 'Terminated'
        id: destroy-env
        run: |
          eb init ${{ vars.AWS_EB_APP_NAME }} --platform "${{ vars.AWS_EB_PLATFORM }}" --region ${{ vars.AWS_REGION }} 
          eb terminate ${{ steps.aws-env-name.outputs.aws-env-name }} --force
      - name: Update Pull Request (Success)
        uses: actions/github-script@v6
        if: success()
        continue-on-error: true
        with:
          script: |
            const comment = `### 🚀 destroy Completed.`

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issuse-number.outputs.issue-number }},
              body: comment
            })
      - name: Update Pull Request (Failure)
        uses: actions/github-script@v6
        if: failure()
        continue-on-error: true
        with:
          script: |
            const comment = `### 🛑 Destroy Failed.

            [View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issuse-number.outputs.issue-number }},
              body: comment
            })
      - name: get deployment id
        id: deployment-id
        uses: actions/github-script@v6
        with:
          script: |
            const prRef = ${{ steps.get-head-ref.outputs.result }};
            // 2. Fetch deployments created specifically for this PR branch
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: prRef
            });

            // 3. Extract the deployment ID if available
            if (deployments.length > 0) {
              const deploymentId = deployments[0].id;
              console.log(`Deployment ID for PR ref '${prRef}': ${deploymentId}`);
              
              // Set output so subsequent steps can use it
              core.setOutput('deployment_id', deploymentId);
            } else {
              console.log(`No deployments found for PR ref '${prRef}'`);
            }
      - name: delete the deployment in the github
        if: steps.destroy-env.conclusion == 'success' && steps.deployment-id.outputs.deployment_id != ''
        uses: actions/github-script@v6
        with:
          script: | 
            const deployment_id = "${{ steps.deployment-id.outputs.deployment_id }}";
            
            // 1. Set status to inactive (required by GitHub before deletion)
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: parseInt(deployment_id),
              state: 'inactive'
            });

            const response = await github.rest.repos.deleteDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: parseInt(deployment_id)
            });
      


  
  
