name: destroy the env
on:
  issue_comment:
    types: created
  pull_request_target: 
    types: closed

jobs:
  destroy-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github.event) }}'
      - run: echo '${{ toJson(github.ref) }}'