name: Deploy on comment
on:
    issue_comment: 
        types: created

jobs:
    deploy-to-new-env:
        runs-on: ubuntu-latest
        permissions: 
            actions: write
        if: github.event.issue.pull_request && github.event.issue.state == 'open' && github.event.comment.body == '/deploy'
        steps:
          - name: get the pull head ref
            id: get-head-ref
            uses: actions/github-script@v6
            with:
              result-encoding: string
              script: |
                const response = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number 
                })
                console.log(response);
                return response.data.head.ref
          - name: trigger a branch deploy
            uses: actions/github-script@v6
            with: 
              script: | 
                const response = github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "deploy.yaml",
                ref: "${{ steps.get-head-ref.outputs.result }}",
                inputs:{
                    "aws-env": `nextjs-starter2-demo-pr-${context.issue.number}`,
                    "github-env": "staging",
                    "report-pr": `${context.issue.number}`
                    }
                });
                console.log(response);

