name: test
on:
    workflow_call:
        
jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: "npm"
            - name: install dependencies
              run: npm ci
            - name: format check
              run: npm run format
            - name: linting check
              run: npm run lint
            - name: checking type errors
              run: npm run typecheck 
            - name: building the next
              run: npm run build
            - name: uploading the next folder to artifact
              uses: actions/upload-artifact@v4
              with:
                name: next folder
                path: .next/
            - name: unit test
              run: npm run test
            - name: uploading the coverage file
              if: always()
              uses: actions/upload-artifact@v4
              with: 
                name: coverage
                path: coverage/
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
            - name: e2e test
              run: npm run test:e2e
            - name: uploading the playwright file
              if: always()
              uses: actions/upload-artifact@v4
              with: 
                name: playwright-report
                path: playwright-report/
            - name: The Slack GitHub Action
              uses: slackapi/slack-github-action@v4
              if: failure()
              with:
                payload: |
                    {
                    "blocks": [
                        {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "🛑 *<https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}|${{ github.workflow }} workflow run>* failed."
                        }
                        }
                    ]
                    }
              env:
                SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
            
                