name: test
on:
    workflow_call:
        
jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: "npm"
            - name: install dependencies
              run: npm ci
            - name: format check
              run: npm run format:fix
            - name: linting check
              run: npm run lint
            - name: checking type errors
              run: npm run typecheck 
            - name: building the next
              run: npm run build
              env:
                FLAGSMITH_ENVIRONMENT_KEY: ${{ secrets.FLAGSMITH_ENVIRONMENT_KEY }}
            - name: uploading the next folder to artifact
              uses: actions/upload-artifact@v4
              with:
                name: next folder
                path: .next/
            - name: unit test
              run: npm run test
            - name: uploading the coverage file
              if: always()
              uses: actions/upload-artifact@v4
              with: 
                name: coverage
                path: coverage/
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
            - name: Install Playwright browsers
              run: npx playwright install --with-deps
            - name: e2e test
              run: npm run test:e2e
              env:
                FLAGSMITH_ENVIRONMENT_KEY: ${{ secrets.FLAGSMITH_ENVIRONMENT_KEY }}
            - name: uploading the playwright file
              if: always()
              uses: actions/upload-artifact@v4
              with: 
                name: playwright-report
                path: playwright-report/
            
            - name: Send Slack notification
              uses: slackapi/slack-github-action@v4
              if: failure()
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK }}
                webhook-type: incoming-webhook
                payload: |
                    {
                        "blocks": [
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "🛑 *<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|CI workflow run>* failed."
                            }
                        }
                        ]
                    }
            
                